#ifndef MyFrame1_H
#define MyFrame1_H

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/wx.h>

/** Implementing MyFrame1 */
class MyFrame1 : public GUI {


	protected:
		// Handlers for MyFrame1 events.
		void FrameOnUpdateUI(wxUpdateUIEvent& event);
		void _loadButtonOnButtonClick(wxCommandEvent& event);
		void _cenzuraButtonOnButtonClick(wxCommandEvent& event);
		void _erodeButtonOnButtonClick(wxCommandEvent& event);
		void _checkBoxOnCheckBox(wxCommandEvent& event);
	public:
		/** Constructor */
		MyFrame1() : GUI(NULL) {
			_image = new wxImage();
			wxInitAllImageHandlers();
		}//// end generated class members

		~MyFrame1() {
			delete _image;
		}
private:
	wxImage * _image, _image1;
	void refresh(wxClientDC &dc);
};

#endif // MyFrame1_H