#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

class Matrix4;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void m_button_load_geometry_click( wxCommandEvent& event );
		void Scrolls_Updated( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		//tworzenie macierzy przekszta³ceñ
		
		
	  void Repaint();
	  //metody tworzace macierze transformacji
	  Matrix4 translation(float, float, float);
	  Matrix4 center();
	  Matrix4 rotation_x(float);
	  Matrix4 rotation_y(float);
	  Matrix4 rotation_z(float);
	  Matrix4 scale(float, float, float);


};

#endif // __GUIMyFrame1__
