#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel1OnPaint( wxPaintEvent& event );
		void m_panel1OnUpdateUI( wxUpdateUIEvent& event );
		void m_button_saveOnButtonClick( wxCommandEvent& event );
		void m_check_bananaOnCheckBox( wxCommandEvent& event );
		void m_scrollBar1OnScroll( wxScrollEvent& event );
		void m_button_star_colorOnButtonClick( wxCommandEvent& event );
		void m_textCtrl1OnText( wxCommandEvent& event );
		void m_choice_shapeOnChoice( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void draw(wxClientDC & dcClient);
		~GUIMyFrame1();

	private:
		enum figure { star = 0, moon = 1, sun = 2 };

		bool _isBananaActivated;
		int _bananaPosition;
		int _chosenFigure;

		wxColour _starColour;
		wxBitmap * _banana;
		wxString _textString;
		wxPoint _starPosition[5];
		wxImageHandler * _imageHandler;
		wxFileDialog * _fileDialog;
	

		



};

#endif // __GUIMyFrame1__
